(specifications->manifest
 '(
   "emacs-native-comp"
   "emacs-better-defaults"
   "emacs-auto-complete"
   "emacs-hydra"
   "emacs-modus-themes"
   "emacs-dash"
   "emacs-lispy"
   "emacs-geiser"
   "emacs-geiser-guile"
   "emacs-ac-geiser"
   "emacs-guix"
   "emacs-yasnippet"
   "emacs-yasnippet-snippets"
   "emacs-with-editor"
   "emacs-pdf-tools"
   ))
