(specifications->manifest 
  '("tree-sitter-c"
    "tree-sitter-c"
    "tree-sitter-cpp"
    "tree-sitter-cmake"
    "tree-sitter-qmljs"
    ;; "tree-sitter-r"
    "tree-sitter-go"
    "tree-sitter-gomod"
    ;; "tree-sitter-cl"
    "tree-sitter-css"
    "tree-sitter-html"
    ;; "tree-sitter-org"
    "tree-sitter-bibtex"
    ;; "tree-sitter-php"
    "tree-sitter-bash"
    "tree-sitter-lua"
    "tree-sitter-java"
    "tree-sitter-json"
    "tree-sitter-ruby"
    "tree-sitter-rust"
    "tree-sitter-julia"
    ;; "tree-sitter-elm"
    "tree-sitter-haskell"
    ;; "tree-sitter-ocaml"
    ;; "tree-sitter-elixir"
    "tree-sitter-python"
    ;; "tree-sitter-racket"
    "tree-sitter-scheme"
    ;; "tree-sitter-c-sharp"
    ;; "tree-sitter-scala"
    "tree-sitter-clojure"
    ;; "tree-sitter-haskell"
    ;; "tree-sitter-markdown"
    "tree-sitter-javascript"
    "tree-sitter-typescript"
    ;; "tree-sitter-markdown-gfm"

    ;; this requires -L $HOME/.dotfiles and a custom package
    "tree-sitter-tcl"))
