env = GDK_SCALE,1
monitor=,preferred,auto,auto

# Outputs
$m1port=eDP-1
$m1desc=AU Optronics 0x559C
$m1res=1920x1080
$m1mode=$m1res@60.00

$m2port = HDMI-A-1
$m2desc = Samsung Electric Company U28D590
$m2res=3840x2160
$m2mode=$m2res@30.00Hz
$m2transform=0

monitorv2 {
  output = $m1port
  mode = $m1mode
  # position = 1480x1440
  position = 0x1440
  scale = 1.0
}

monitorv2 {
  output = $m2port
  mode = $m2mode
  position = 0x0
  scale = 1.5
}
