# unless dumbterm
if [ "$TERM" != "dumb" ]; then
    # commandline color by default

    if [[ ! -f "/var/lib/pacman/sync/omarchy.files" ]]; then
        # omarchy uses lza pretty deeply
        alias ls='ls --color=auto'
    fi
    alias dir='dir --color=auto'
    alias egrep='egrep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias diff='diff --color=auto'
    alias grep='grep --color=auto'
    alias vdir='vdir --color=auto'
    alias less='less -R'
    alias ress='less'
# else
    # no color
fi

alias covia='sed -e "s/:/\n:\t/g"'
alias dfs='df -h | tail -n+2 | sort -nk5'
alias dfsh='df -sh | tail -n+2 | sort -nk5'
# alias diff='diff --color=auto'
alias diffia='envia | covia | diff - <(env | envia | covia)'
alias diffusb='diff <(lsusb) <(sleep 3; lsusb)'
alias difnia='nenvia | diff - <(env | nenvia)'
# alias dir='dir --color=auto'
# alias egrep='egrep --color=auto'
alias envia='grep -e '\''^[A-Za-z0-9_]*PATH='\'' | sort | uniq'
# alias fgrep='fgrep --color=auto'
alias bashbinds="bind -p | grep -ve '^#' | tr -d ':\"' | sed -e 's/\\\\e/M /g' | sed -e 's/\\\\C-/C /g' | grep -v 'self-insert' | sort -k2"
alias bashbindtree="bind -P | cut -f1 -d' ' | tr '-' '/' | tree --noreport --fromfile ."
alias gkcfg='git stack --dump-config -'
alias gkg='git stack'
alias gksy='git stack sync'
alias gpga='gpg --armor'
alias gpgk='gpg-connect-agent killagent /bye'
alias gpgrel='gpg-connect-agent reloadagent /bye'
alias gpguptty='gpg-connect-agent updatestartuptty /bye'
# alias grep='grep --color=auto'
alias grubup='sudo update-grub'
alias gxpl='rlwap guix repl'
alias hcbdoops='hcbinds | sort | cut -f2-5 | uniq -c | grep -vE "^\s+1"'
alias hcbinds='hyprctl binds | tr -d "\n" | sed -e "s/bind/\nbind/g"'
alias hcx='hyprctl'
alias hw='hwinfo --short'
alias imacs='emacs -T "¤ INFO" -f info-standalone --eval="(load-theme (intern \"wombat\"))"'
alias iotopa='iotop -oa'
alias jctl='isd'
alias jctlb='journalctl -xb'
alias jctlb7='journalctl -xb -p7'
alias jctlu='journalctl --user'
alias jctlu7='journalctl --user -p7'
alias jour='isd'
alias jqr='jq -r '
alias jqrj='jq -rj '
# alias l='ls -alh'
# alias ll='ls -l'
# alias ls='ls --color=tty'
alias nenvia='grep -ve '\''^[A-Za-z0-9_]*PATH='\'' | sort | uniq'
alias pathtr='tr ":" "\n"'
alias ps_nice='ps -o pid,ppid,uname,cls,nice,pri,rtprio,comm,args --sort=-nice'
alias ps_pri='ps -eo pri k +pri h | uniq -c'
alias psid='ps -opid,uid,command h'
alias psmem='ps auxf | sort -nr -k 4'
alias psmem10='ps auxf | sort -nr -k 4 | head -10'
alias psnice='ps axo pid,ppid,uname,cls,nice,pri,rtprio,comm,args --sort=-nice'
alias pspri='ps -eo pid,tid,class,rtprio,ni,pri,psr,pcpu,stat,wchan:14,comm k pri'
alias psz='ps axo s,pid,ppid,uname,comm,args | grep -e"^Z"'
alias pssyuz='ps axo s,pid,ppid,unit,ouid,uunit,slice,uname,comm,args | grep -e"^Z"'
alias ptrgb='pstree -C age -pT'
alias shitbin='echo -e "\033c"'
alias sqli='rlwrap sqlite3'
alias sycat='SYSTEMD_COLORS=256 systemctl cat --no-pager'
alias sysdpath='systemd-path system-shared'
alias systat='systemctl status'
alias sysu='isd'
alias sysupath='systemd-path user-shared'
alias syu='systemctl --user'
alias syucat='SYSTEMD_COLORS=256 systemctl cat --user --no-pager'
alias syustat='systemctl --user status'
alias syusvc='systemctl --user list-units   | cut -f3 -d'\'' '\''   | grep -e '\''service$'\'''
alias syutgt='systemctl --user list-units     | cut -f3 -d'\'' '\''     | grep -e '\''\.target$'\'''
alias tarnow='tar -acf '
alias treef='tree --prune -aP'
alias tyxy='tidy --quiet yes --tidy-mark no --vertical-space yes -indent -xml'
alias untar='tar -zxvf '
# alias vdir='vdir --color=auto'
alias wget='wget -c '
alias wordcat='tee >(xargs -n1 cat) | wc -w'
