:PROPERTIES:
:ID:       2b7dae76-003f-4714-b621-c046d855fe3e
:END:
#+TITLE: Ansible: setup a portable environment on Guix
#+CATEGORY: slips
#+property: header-args            :tangle-mode (identity #o400) :mkdirp yes
#+property: header-args:conf       :tangle-mode (identity #o400) :mkdirp yes
#+property: header-args:shell      :tangle-mode (identity #o500) :mkdirp yes
#+property: header-args:bash       :tangle-mode (identity #o500) :mkdirp yes
#+property: header-args:scheme     :tangle-mode (identity #o500) :mkdirp yes
#+property: header-args:emacs-lisp :tangle-mode (identity #o600) :mkdirp yes
#+TAGS:

* Org Babel Config

** Var Setup

#+name: ansible-bindings
| Var              | Value        |
| ansible-home-var | ANSIBLE_HOME |
| secrets-home-var | SECRETS_HOME |

#+begin_src emacs-lisp :var bindings=ansible-bindings :colnames yes :results silent
(let* ((ansible-home-var (cadr (or (assoc "ansible-home-var" bindings)
                                   '(""))))
       (secrets-home-var (cadr (or (assoc "secrets-home-var" bindings)
                                   '("")))))
  (setq secrets-home (or (getenv secrets-home-var) ".")
        ansible-home (or (getenv ansible-home-var) secrets-home)))

;; better just use the environment var
;; (eval (car (read-from-string ansible-home-string)))
#+end_src

To add in bash scripts as =<<ansible-home>>=

#+name: ansible-home_CALL
#+begin_src emacs-lisp :results silent
ansible-home
#+end_src

#+name: secrets-home_CALL
#+begin_src emacs-lisp :results silent
secrets-home
#+end_src

** Use in templates

After evaluating the above, then the following blocks will eval =ansible-home=
in their headers or bodies. =:results silent= should ensure that these paths
don't end up in this file.

#+begin_example org
#+begin_src emacs-lisp
ansible-home
#+end_src
#+end_example

This file should be tangled with =C-c C-v C-t= to ensure that lisp blocks are run to populated these values. If emacs is already open, then running =M-: (setenv "VAR" "value")= will set the environment var for the whole process. This is also useful for setting:

+ =SSH_AUTH_SOCK=
+ =SSH_AGENT_PID=
+ =GPG_TTY=


* Environment

** Ansible 2.9 Notes

** Guix Profile

See "Ansible On Guix" for info on its dependencies

#+begin_src scheme :tangle (concat secrets-home "/.config/guix/manifests/ansible-usb.scm")
(specifications->manifest
 '(
   "ansible"
   ))
#+end_src

Build the relocatable guix profile:

#+begin_src shell :eval no
guixpkg=$(guix pack --relocatable --system=x86_64-linux --compression=gzip --save-provenance \
      -L $HOME/.dotfiles -m $SECRETS_HOME/.config/guix/manifests/ansible-usb.scm \
      -S .bin=bin)
if [ ! -e $SECRETS_HOME/pkg ]; then
    mkdir -p $SECRETS_HOME/pkg
fi
cp $guixpkg $SECRETS_HOME/pkg
#+end_src

The package is built to =/gnu/store= and is in =$guixpkg=. Now unpack:

#+begin_src shell :eval no
tar -C $SECRETS_HOME/pkg -xzvf $guixpkg
#+end_src

The profile will be in =./gnu/store/*profile=. If there are multiple profiles
found in =$SECRETS_HOME=, then searching the =.tar= is a better way to find the
profile.

#+begin_src shell :eval no
guixprofile=$(tar --list -zf $guixpkg | grep 'profile/bin' | cut -d/ -f4)
ln -s $SECRETS_HOME/pkg/gnu/store/$guixprofile $SECRETS_HOME/.guix-ansible
#+end_src

Test the profile's binaries in a clean shell with:

#+begin_src shell :eval no
guix shell --profile=.guix-ansible -- bash
#+end_src

** Init Script

#+begin_src shell :tangle (concat secrets-home "/init-ansible.sh") :noweb yes
export SECRETS_HOME=$(pwd)
#export SECRETS_HOME="<<secrets-home_CALL()>>"
export ANSIBLE_HOME="<<ansible-home_CALL()>>"

# TODO: move this to an =init.sh= file
export PATH=$SECRETS_HOME/.bin:$PATH

export GUIX_ANSIBLE=$SECRETS_HOME/.guix-ansible
export GUIX_EXTRA=$HOME/.guix-extra-profiles

if [ -f $GUIX_ANSIBLE/etc/profile ]; then
  GUIX_PROFILE=$GUIX_ANSIBLE
  source $GUIX_ANSIBLE/etc/profile
else
  echo "$GUIX_ANSIBLE not found. Trying $GUIX_EXTRA"
  if [ -d $GUIX_EXTRA ]; then
    GUIX_PROFILE=$GUIX_EXTRA/ansible/ansible
    source $GUIX_EXTRA/ansible/ansible/etc/profile
  else
    echo "$GUIX_PROFILE not found. access ansible* some other way"
    return 123
  fi
fi
#+end_src

** Python/Pip

The Guix =ansible= package brings its own python, where its deps are located. It needs to be specified in =ansible.cfg=.

**** TODO how to handle need for additional pip dependencies?

** Ansible Config

Run =ansible-config init --disabled -t all > $ANSIBLE_HOME/ansible.cfg.defaults= to generate defaults.

#+begin_src conf :tangle (concat ansible-home "/ansible.cfg.eg")
[defaults]
# forks=15
timeout=240
nocows=1

# will support faster network operations
# pipelining=True
# become=True

transport=ssh
# host_key_checking=False
# host_key_auto_add=True
# pkcs11_provider =
# ssh_args
# ssh_common_args
# ssh_executable
# ssh_extra_args
# ssh_transfer_method

remote_tmp = $HOME/.ansible/tmp
local_tmp = $SECRETS_HOME/.ansible/tmp

retry_files_enabled=False
ansible_debug=True
# deprecation_warnings=False

hash_behavior=merge
gathering=smart
fact_caching=jsonfile
fact_caching_connection=$SECRETS_HOME/.ansible/tmp
stdout_callback=yaml
# callback_whitelist=profile_tasks,jsnapy,slack,logstash
# callback_whitelist=profile_tasks

# library=./files/ansible/library
# collections_paths=./collections
roles_path=./roles # :/etc/ansible/roles
inventory=./inventory.yml
log_path=$SECRETS_HOME/.ansible/tmp/ansible.log

[persistent_connection]
command_timeout=45
#+end_src

Also, plugins for visibility/logging:

#+begin_example conf
# [callback_slack]
# channel = #thechannel
# username = fdsa
# webhook_url = env:SLACK_WEBHOOK_URL

# [callback logstash]
# port = env:LOGSTASH_PORT
# server = env:LOGSTASH_SERVER
# type = env:LOGSTASH_TYPE
#+end_example

**** TODO change =./tmp= locations?
**** TODO include other collections/roles paths?


** Inventory Skel

#+begin_src conf :tangle (concat ansible-home "/inventory.ini.eg")

#+end_src

** SSH

**** TODO make tangled scripts portable (or move org file)

* Playbooks




* External Services

** Galaxy

** AWX

* Ansible on Guix


The =ansible-core= package includes:

+ native:
  - openssl/openssh
  - python inputs for mocking/testing
+ inputs:
  - libselinux
  - sshpass
  - python
    - paramiko
    - passlib
    - pexpect
+ propagated
  - python
    - cryptography
    - jinja2
    - pyyaml
    - packaging
    - resolvelib-0.5
