:PROPERTIES:
:ID:       025a21e3-a2cb-455b-9266-dc2d6f95df73
:END:
#+TITLE: KDE Desktop
#+PROPERTY: header-args :mkdirp yes
#+PROPERTY: header-args:sh   :tangle-mode (identity #o555)
#+PROPERTY: header-args:conf :tangle-mode (identity #o555)
#+OPTIONS: toc:nil


* Table of Contents :TOC_3_gh:
    - [[#taking-a-break-from-sway][Taking A Break From Sway]]
- [[#system-settings][System Settings]]
- [[#fonts][Fonts]]
- [[#input][Input]]
  - [[#fcitx5][FCITX5]]
- [[#kwin][KWin]]
  - [[#plugins][Plugins]]
- [[#panel-latte][Panel (Latte)]]
- [[#plasma][Plasma]]
- [[#xdg][XDG]]
- [[#applications][Applications]]
  - [[#x11-tools][X11 Tools]]

*** Taking A Break From Sway

So, for whatever reason, Sway is incredibly unstable for me. There seem to be
some problematic apps (Slack, Discord, Emacs pGTK). I think it's probably that
my graphics card is too old to be well-supported by Nouveau drivers. Whatever it
was didn't reliably leave coredumps and consistently smashed the Wayland pipes,
forcing a restart.

This is a temporary desktop configuration for KDE/X11. It is intended to
generate any config files for KDE that can't simply be linked in. For now, the
intent for =KDE.org= is to generate into the same =$HOME= and =$XDG_CONFIG_HOME=
that I would use for Sway or other WM's -- if I need to switch back to sway,
then tangling =Desktop.org= and then making one or two changes to =Bash.org=
should do it. I spent too much time thinking about "the right way" to support
multiple deployments or WM's, but never found anything satisfactorily better
than basic.

* System Settings

* Fonts

* Input

** FCITX5

**

* KWin

** Plugins

* Panel (Latte)


* Plasma


* XDG


* Applications

** X11 Tools
