$wsDiscord=discord
$wsDiscordKey=Delete
$wsDiscordMon=$m2port

# hyprlang if HYPRHOSTKHARIS
$wsDiscordLaunch=omarchy-launch-webapp https://discord.com/channels/@me
# hyprlang endif
# hyprlang if HYPRHOSTKRATOS
$wsDiscordMon=$m3port
$wsDiscordLaunch=uwsm app -- chromium --app="https://discord.com/channels/@me"
# hyprlang endif

workspace = name:$wsDiscord, monitor:$wsDiscordMon, bordersize:5, on-created-empty:[float] $wsDiscordLaunch
bindd = SUPER ALT, $wsDiscordKey, 'Switch to workspace: discord', workspace, name:$wsDiscord
bindd = SUPER SHIFT ALT, $wsDiscordKey, 'Move window to workspace: discord', movetoworkspacesilent, name:$wsDiscord

$wsScratchSize=90% 90%
windowrule = workspace name:$wsDiscord, match:class (chrome-discord.com.*)
windowrule = float 1, match:class (chrome-discord.com.*)
windowrule = size $wsScratchSize, match:class (chrome-discord.com.*)
windowrule = move 10% 10%, match:class (chrome-discord.com.*)

windowrule = workspace name:$wsDiscord, match:class (discord)
windowrule = float 1, match:class (discord)
windowrule = size $wsScratchSize, match:class (discord) # otherwise starts in 4:3
windowrule = move 10% 10%, match:class (discord)

windowrule = workspace name:$wsDiscord, match:class (vesktop)
windowrule = float 1, match:class (vesktop)
windowrule = size $wsScratchSize, match:class (vesktop) # otherwise starts in 4:3
windowrule = move 10% 10%, match:class (vesktop)
