$wsDocs = docs
$wsDocsKey = d
$wsDocsMon = $m2port


# hyprlang if HYPRHOSTKHARIS
# $wsDiscordLaunch=omarchy-launch-webapp https://discord.com/channels/@me
$wsDiscordLaunch=uwsm app -- zeal
# hyprlang endif
# hyprlang if HYPRHOSTKRATOS
# $wsDiscordLaunch=flatpak run com.discordapp.Discord
$wsDiscordLaunch=flatpak run org.zealdocs.Zeal
# hyprlang endif

workspace = special:$wsDocs, on-created-empty:[float] $wsDiscordLaunch
bind = SUPER, $wsDocsKey, togglespecialworkspace, $wsDocs
bind = SUPER ALT, $wsDocksKey, movetoworkspacesilent, special:$wsDocs
windowrule = workspace special:$wsDocs, match:class (org.zealdocs.Zeal)
windowrule = float 1, match:class (org.zealdocs.Zeal)
windowrule = size 1920 1080, match:class (org.zealdocs.Zeal)
