#!/bin/sh
export GUIX_SOURCE=$_ECTO/guix/guix
export EMACS_SOURCE=$_ECTO/emacs/emacs/src

guix shell -E "^EMAIL$" \
     -E 'EMACS_SOURCE' \
     -E 'GUIX_SOURCE' \
     -p $GUIX_EXTRA/emacs-g/emacs-g -- \
     emacs "$@"
