#!/bin/sh
DMENU=${DMENU:-dmenu}
prompt="display: "

# xrandr --listmonitors | rev | cut -f1 -d " " -s | rev
# TODO create a separate script for remapping wacom to all displays
# connected_displays=$()
# connected_displays=$connected_displays ALL

selected_display=$(xrandr --listmonitors | tail -n+2 | awk '{ print $NF; }' | ${DMENU} -p $prompt)
#[[ $selected_display -eq "ALL" ]] && selected_display=ALL

tablet=$(xsetwacom list devices | awk -F "id:" '{ print $2; }' | grep PAD | cut -f1 | xargs)
stylus=$(xsetwacom list devices | awk -F "id:" '{ print $2; }' | grep STYLUS | cut -f1 | xargs)
eraser=$(xsetwacom list devices | awk -F "id:" '{ print $2; }' | grep ERASER | cut -f1 | xargs)

#xsetwacom set "${tablet}" MapToOutput $selected_display
xsetwacom set "${stylus}" MapToOutput $selected_display
xsetwacom set "${eraser}" MapToOutput $selected_display
