(define-module (ellipsis packages tree-sitter)
  #:use-module ((guix licenses) #:prefix license:)
  #:use-module (gnu packages)
  #:use-module (gnu packages base)
  ;;  #:use-module (gnu packages crates-graphics)
  ;;  #:use-module (gnu packages crates-io)
  #:use-module (gnu packages node)
  #:use-module (gnu packages tree-sitter)
  ;; #:use-module (guix build-system cargo)
  ;; #:use-module (guix build-system gnu)
  #:use-module (guix build-system tree-sitter)
  #:use-module (guix gexp)
  #:use-module (guix download)
  #:use-module (guix git-download)
  ;; #:use-module (guix hg-download)
  #:use-module (guix packages)
  #:use-module (guix utils)
  #:use-module (srfi srfi-1))

(define-public foo "foo")

