;;; Copyright © 2025 David Conner <aionfork@gmail.com>
(define-module (dc home aliases)
  #:export (dc-aliases))

(define dc-aliases
  '(("cleanup" . "sudo pacman -Rns `pacman -Qtdq`")
    ("diff" . "diff --color=auto")
    ("dir" . "dir --color=auto")
    ("egrep" . "egrep --color=auto")
    ("emacs-debug-wayland" . "WAYLAND_DEBUG=1 emacs --fg-daemon > $HOME/.cache/log/emacs.wayland.`date +%Y-%m%d-%H%M`.log 2>&1")
    ("fgrep" . "fgrep --color=auto")
    ("fixpacman" . "sudo rm /var/lib/pacman/db.lck")
    ("gkcfg" . "git stack --dump-config -")
    ("gkg" . "git stack")
    ("gksy" . "git stack sync")
    ("gpga" . "gpg --armor")
    ("gpgk" . "gpg-connect-agent killagent /bye")
    ("gpgrel" . "gpg-connect-agent reloadagent /bye")
    ("gpguptty" . "gpg-connect-agent updatestartuptty /bye")
    ("grep" . "grep --color=auto")
    ("grepnobin" . "grep -I")
    ("grubup" . "sudo update-grub")
    ("hw" . "hwinfo --short")
    ("iotopa" . "iotop -oa")
    ("jctl" . "journalctl -p 3 -xb")
    ("jctlu" . "journalctl --user -u")
    ("ls" . "ls --color=auto")
    ("nodenpm_lsparse" . "npm ls -g --parseable | grep node_modules | sed -e '\\''s/.*node_modules\\///g'\\''")
    ("pathtr" . "tr '\\'':'\\'' '\\''\\n'\\''")
    ("ps_nice" . "ps axo pid,comm,nice,cls --sort=-nice")
    ("ps_pri" . "ps -eo pri k +pri h | uniq -c")
    ("psid" . "ps -opid,uid,command h")
    ("psmem" . "ps auxf | sort -nr -k 4")
    ("psmem10" . "ps auxf | sort -nr -k 4 | head -10")
    ("psnice" . "ps -o pid,comm,nice")
    ("pspri" . "ps -eo pid,tid,class,rtprio,ni,pri,psr,pcpu,stat,wchan:14,comm k pri")
    ("ptrgb" . "pstree -C age -pT")
    ("rip" . "expac --timefmt='\\''%Y-%m-%d %T'\\'' '\\''%l\\t%n %v'\\'' | sort | tail -200 | nl")
    ("rmpkg" . "sudo pacman -Rdd")
    ("screen" . "screen -h 2000")
    ("shitbin" . "echo -e \"\\033c\"")
    ("sshddump" . "sudo sshd -T")
    ("sysdpath" . "systemd-path system-shared")
    ("sysu" . "systemctl --user")
    ("sysupath" . "systemd-path user-shared")
    ("tarnow" . "tar -acf ")
    ("treef" . "tree --prune -aP")
    ("untar" . "tar -zxvf ")
    ("upd" . "/usr/bin/update")
    ("vdir" . "vdir --color=auto")
    ("wget" . "wget -c ")))
