;;; .doom.d/modules/dc-bufler.el -*- lexical-binding: t; -*-

(defun dc/bufler-enable-prism-faces (arg)
  (interactive "P")
  ;; disable when arg
  (if arg
      (progn (remove-hook 'bufler-list-mode-hook #'prism-mode)
             (setq bufler-face-prefix "outline-"))
    (add-hook 'bufler-list-mode-hook #'prism-mode)
    (setq bufler-face-prefix "prism-faces-")))

(defun dc/bufler-set-groups ()
  "This only seems to eval setf once."
  (interactive)
  (setf bufler-groups (dc/bufler-defgroups)))

(defun dc/bufler-defgroups ()
  "Run `bufler-defgroups'"
  (bufler-defgroups
    (group (auto-workspace))
    (group (group-or "*Help/Info*"
                     (mode-match "*Help*" (rx bos "help-"))
                     (mode-match "*helpful*" (rx bos "helpful"))
                     (mode-match "*Info*" (rx bos "info-"))))
    (group (group-and "*Special*"
                      (lambda (buffer)
                        (unless (or (funcall (mode-match "Magit" (rx bos "magit-status")) buffer)
                                    (funcall (mode-match "Dired" (rx bos "dired")) buffer)
                                    (funcall (auto-file) buffer))
                          "*Special*")))
           (group (name-match "**Special**"
                              (rx bos "*" (or "Messages" "Warnings" "scratch" "Backtrace") "*")))
           (group (mode-match "*Magit* (non-status)" (rx bos (or "magit" "forge") "-"))
                  (auto-directory))
           (mode-match "*Helm*" (rx bos "helm-"))
           (auto-mode))

    (group (dir "~/forge" 1)
           (group (auto-project)
                  (group-not "*special*" (auto-file))
                  (auto-mode)))
    (group (dir "~/Work/tries" 1)
           (group (auto-indirect) (auto-file))
           (group-not "*special*" (auto-file))
           (auto-mode))

    (group (dir "~/.dotfiles")
           (group (auto-indirect) (auto-file))
           (group-not "*special*" (auto-file))
           (auto-mode))
    ;; (group (dir (if (bound-and-true-p doom-user-dir) doom-user-dir "~/.doom.d"))
    ;;        (group (auto-indirect) (auto-file))
    ;;        (group-not "*special*" (auto-file))
    ;;        (auto-mode))
    (group (dir "/data/ecto/frc" 1)
           (group (auto-indirect) (auto-file))
           (group-not "*special*" (auto-file))
           (auto-mode))
    (group (dir "/data/ecto/x.files" 1)
           (group (auto-project)
                  (group-not "*special*" (auto-file))
                  (auto-mode)))
    (group (dir "/data/ecto/nixos" 1)
           (group (auto-indirect) (auto-file))
           (group-not "*special*" (auto-file))
           (auto-mode))
    (group (dir "/data/ecto/guix/channels" 1)
           (group (auto-indirect) (auto-file))
           (group-not "*special*" (auto-file))
           (auto-mode))
    (group (dir "/data/ecto/guix" 1)
           (group (auto-indirect) (auto-file))
           (group-not "*special*" (auto-file))
           (auto-mode))
    (group (dir "/data/repo")
           (group (auto-indirect) (auto-file))
           (group-not "*special*" (auto-file))
           (auto-mode))
    (group (dir (if (bound-and-true-p org-directory) org-directory "~/org"))
           (group (auto-indirect) (auto-file))
           (group-not "*special*" (auto-file))
           (auto-mode))
    (group (dir (if (file-exists-p (expand-file-name ".local/straight/repos" user-emacs-directory))
                    (expand-file-name ".local/straight/repos" user-emacs-directory) "~/.emacs.doom/.local/straight/repos"))
           (group (auto-indirect) (auto-file))
           (group-not "*special*" (auto-file))
           (auto-mode))
    (group (dir "/gnu/store/")
           (group (auto-indirect) (auto-file))
           (group-not "*special*" (auto-file))
           (auto-mode))
    (group (dir "/nix/store/")
           (group (auto-indirect) (auto-file))
           (group-not "*special*" (auto-file))
           (auto-mode))

    ;; (group (auto-projectile))
    ;; (group (auto-project))
    ;; (dir user-emacs-directory)
    ;; (auto-directory)

    (auto-mode)))

;; preemptively hide dired in several layers (use bufler-filter-buffer-modes)
;;
;; (group (group-and "*Dired*" (mode-match "Dired" (rx bos "dired")))
;;        (group
;;         (group-and "*Dired2*" (mode-match "Dired" (rx bos "dired")))
;;         (group (group-and "*Dired3*" (mode-match "Dired" (rx bos "dired")))
;;                (auto-file))))

(provide 'dc-bufler)
